### ISSUE TITLE
 AttributeError: module 'keyrings.alt' has no attribute 'file'

### ISSUE THREAD

**Issue by elig0n** [GustavoKatel/pushbullet-cli#99]
```
Traceback (most recent call last):
  File "/usr/bin/pb", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pushbullet_cli/app.py", line 94, in main
    if isinstance(keyring.get_keyring(), keyrings.alt.file.EncryptedKeyring):
AttributeError: module 'keyrings.alt' has no attribute 'file'
```

I found that `pb` `app.py` has to explicitly import `keyrings.alt.file` because neither `keyrings.alt` nor `keyrings.alt.file` would be accessible if it simply import keyrings alone.

* OS: arch linux
* Python 3.9.1
* keyring==21.4.0
* keyrings.alt==4.0.2

**Comment by ReneFroger** [comment]
I have the same problem with the `keyrings.alt` in installation, since Pip can't find the right version.

**Comment by GustavoKatel** [comment]
hi @elig0n can u try installing from the main branch and see if you still have issues with that?

**Comment by elig0n** [comment]
you mean from git or via pip upgrade?

**Comment by GustavoKatel** [comment]
git please

1. git clone
2. create a virtualenv to not mess with your current installation
3. pip install .
4. try running and see if the error persists

**Comment by GustavoKatel** [comment]
@ReneFroger @elig0n could try v1.2.1? just pushed to pypi

**Comment by elig0n** [comment]
@GustavoKatel seems to work without problems after upgrade to 1.2.1

**Comment by elig0n** [comment]
This issue seems to have returned in version 0.7.5 / 1.2.2 (using Python 3.10)
I have managed to workaround it with:
```python
from keyrings.alt.file import EncryptedKeyring, PlaintextKeyring
```
and then manually specifying those objects.

But then when I try to push something I get:
```python3
Traceback (most recent call last):
  File "/home/user/.local/bin/pb", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
TypeError: push() got an unexpected keyword argument 'file'                               /0.2s
```
